### ISSUE TITLE
[Request] 1.20.1

### ISSUE THREAD

**Issue by ginsm** [Roundaround/mc-fabric-stackables#12]
Any chance of a port to 1.20.1? Thanks! 😄

**Comment by Roundaround** [comment]
It actually works with 1.20.1 already, though I just updated the metadata on Modrinth!

**Comment by Ynaught** [comment]
Any chance this would apply to 1.21 as well?

Edit: 
Just read your "A note about mod updates to 1.20.5/6 and 1.21" memo. I see you have alot of work, online and off. 😅
This question moreso is just asking if the 1.20.5 changes effect this mod in particular as far as 1.21 goes. Only asking cause the post said "many" of your mods and your reply on this issue report shows a history of the mod being unaffected in the past.

I'm mostly just looking for a way for bundles to hold music discs. Struggling to find alternative mods.

**Comment by Roundaround** [comment]
> Any chance this would apply to 1.21 as well?
> 
> Edit: Just read your "A note about mod updates to 1.20.5/6 and 1.21" memo. I see you have alot of work, online and off. 😅 This question moreso is just asking if the 1.20.5 changes effect this mod in particular as far as 1.21 goes. Only asking cause the post said "many" of your mods and your reply on this issue report shows a history of the mod being unaffected in the past.
> 
> I'm mostly just looking for a way for bundles to hold music discs. Struggling to find alternative mods.

Most of the time I actually don't know - I just have to test it on every version to find out. It's possible it'll just work with 1.20.5/6 but with how many files it touches I won't know for sure until I get the time to test it
