### ISSUE TITLE
Suggestion: Add empty shulker boxes as option

### ISSUE THREAD

**Issue by Coastersaurus** [Roundaround/mc-fabric-stackables#15]
Please update to include empty shulker boxes as a stackable option. Thanks.

**Comment by Roundaround** [comment]
Unfortunately shulkers are a lot harder to do. I can increase the max stack size, but then I'd also have to implement some kind of mechanism to check the inventories (and color, name, etc) before trying to combine stacks. It would result in a lot of code that's likely to break with every Minecraft update. It's just simply not something I'm willing to take on
