### ISSUE TITLE
More item suggestions

### ISSUE THREAD

**Issue by sternschnaube** [Roundaround/mc-fabric-stackables#20]
- Horse Armor
- Armor
- Tools
- Totem of Undying

Thanks ☺️

**Comment by sternschnaube** [comment]
Decorated Pots aswell please.

**Comment by Roundaround** [comment]
Added horse armor and totems in 2.0.0! At the moment, 2.0.0 is only out for 1.20.3/1.20.4, but I hope to backport it to 1.20-1.20.2 soon.

Also the 1.20-1.20.2 backport will also include decorated pots. :)

**Comment by sternschnaube** [comment]
Thanks you for the update / clarification 😄
