### ISSUE TITLE
[Bug] Incompatibility with Easy Anvils

### ISSUE THREAD

**Issue by CarlMichaelFabe** [Roundaround/mc-fabric-stackables#25]
When used in conjunction with [Easy Anvils](https://modrinth.com/mod/easy-anvils), items in the anvil do not get consumed.

I tried this with a Netherite Sword and a Sharpness V book. I got the enchanted weapon but the original items stayed in the anvil and did not get consumed.

**Comment by kerrschtein** [comment]
I am getting this as well!

**Comment by Mortycio** [comment]
up

**Comment by eden4eden** [comment]
yep, this is true

**Comment by WaterYouDoing-0** [comment]
Is there any way around this?
other than removing either of the mods of course.

**Comment by Roundaround** [comment]
> Is there any way around this? other than removing either of the mods of course.

As far as I know, no. At least not on my end. Easy Anvils doesn't just change how anvils work - it completely replaces the code responsible for the anvil screen and its inventory/crafting logic, and that replacement makes all the same assumptions of stack size that vanilla anvils do, which means its prone to the same bugs when you increase the stack sizes. The only way to fix the incompatibility would be to fix it within Easy Anvils.
