### ISSUE TITLE
suggestion: add a way to toggle the splash/lingering potion use cooldown

### ISSUE THREAD

**Issue by Briarbot2011** [Roundaround/mc-fabric-stackables#27]
for example, i want to spam splash/lingering potions in creative but i can't because of the use cooldown.

please add a way to either turn off the cooldown or configure it

**Comment by Roundaround** [comment]
Unless I messed something up, the "Splash potion throw delay" config option (`splashPotionDelay` in the config file) controls the delay between throws, and you should be able to turn it down to zero to remove the delay.

I don't have a test instance set up at the moment (and am unfortunately pretty busy) so please let me know if that works!

**Comment by Briarbot2011** [comment]
> Unless I messed something up, the "Splash potion throw delay" config option (`splashPotionDelay` in the config file) controls the delay between throws, and you should be able to turn it down to zero to remove the delay.
> 
> I don't have a test instance set up at the moment (and am unfortunately pretty busy) so please let me know if that works!

oh thanks, i didn't see it in the modmenu config so i didn't think it even existed. i'll try it out.

**Comment by Briarbot2011** [comment]
sorry for not closing it lol i forgot to do so
