### ISSUE TITLE
Suggestion: use tags to allow interactions with other mods.

### ISSUE THREAD

**Issue by jshipley** [Roundaround/mc-fabric-stackables#4]
Right now, it looks like Stackables can only work with vanilla items. This mod would be a lot more useful if I could, for example add a new soup to the c:soups or stackables:soups tag and have that soup also become stackable.

**Comment by Roundaround** [comment]
Oh good idea. I'll work on it for the next version. I always forget about tags 😊

**Comment by nco2k** [comment]
this is a great idea and would solve many problems.

**Comment by Roundaround** [comment]
Done as of 2.0.0/2.0.1! See the latest versions on Modrinth! :)

EDIT: Also you can see all the tags on the mod's description page on Modrinth as well
