### ISSUE TITLE
Buckets and water bottles lose items when used in dispensers

### ISSUE THREAD

**Issue by Roundaround** [Roundaround/mc-fabric-stackables#5]
The vanilla code simply returns "empty bottle/bucket", so it replaces the remaining stack of filled items. Should take a look at and mimic the code for filling honey bottles and how it handles the byproducts

**Comment by alexweber** [comment]
Something similar happens with furnaces and lava buckets where if you put a stack in you only get one empty bucket out the rest are gone,

**Comment by Roundaround** [comment]
Fixed with 1.3.0!
